### ISSUE TITLE
Event reporters

### ISSUE THREAD

**Issue by NoUseFreak** [Cron/Cron#25]
I would consider converting the reporters to an event-driven logic. That would allow other tasks (like logging). What do you think?

Split from #18

**Comment by NoUseFreak** [comment]
This feels like a great idea. Do you have an proposal about the implementation?

**Comment by sagikazarmark** [comment]
I think event-driven logic should always be optional. In most cases people don't need it. If it is possible, I suggest implementing it as some kind of decorator. I am not sure it is possible in this case since there is a relatively complex object graph, but as I can see reporters are used in the executor part, so you could have a decorator for executor. This would also allow to implement multiple dispatchers. For example I usually implement symfony and league event dispatcher use since these are the most popular ones nowadays.
